# Generated by Django 4.2 on 2024-10-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='profile_pics/ACg8ocI8X7tlvNwr7a_F4by0VJhdB0B29wBax3ZIMAb1jId7e8JSzy-ls128-b16-cc-rp-mo.png', null=True, upload_to='profile_pics'),
        ),
    ]
